//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService.DataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetWSQImages", ReplyAction="http://tempuri.org/IDataService/GetWSQImagesResponse")]
        byte[] GetWSQImages(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SetWSQImages", ReplyAction="http://tempuri.org/IDataService/SetWSQImagesResponse")]
        void SetWSQImages(int id, ref byte[] buffer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/saveWsqInDatabase", ReplyAction="http://tempuri.org/IDataService/saveWsqInDatabaseResponse")]
        void saveWsqInDatabase(int id, byte[] buffer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : WindowsService.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<WindowsService.DataService.IDataService>, WindowsService.DataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetWSQImages(string id) {
            return base.Channel.GetWSQImages(id);
        }
        
        public void SetWSQImages(int id, ref byte[] buffer) {
            base.Channel.SetWSQImages(id, ref buffer);
        }
        
        public void saveWsqInDatabase(int id, byte[] buffer) {
            base.Channel.saveWsqInDatabase(id, buffer);
        }
    }
}
