//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCBioIdentification.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedFPScanners {
            get {
                return ((string)(this["SelectedFPScanners"]));
            }
            set {
                this["SelectedFPScanners"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FPUseGeneralization {
            get {
                return ((bool)(this["FPUseGeneralization"]));
            }
            set {
                this["FPUseGeneralization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int FPGeneralizationTemplates {
            get {
                return ((int)(this["FPGeneralizationTemplates"]));
            }
            set {
                this["FPGeneralizationTemplates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint NfeMode {
            get {
                return ((uint)(this["NfeMode"]));
            }
            set {
                this["NfeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Neurotec.Biometrics.NfeTemplateSize NfeTemplateSize {
            get {
                return ((global::Neurotec.Biometrics.NfeTemplateSize)(this["NfeTemplateSize"]));
            }
            set {
                this["NfeTemplateSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Neurotec.Biometrics.NfeReturnedImage NfeReturnedImage {
            get {
                return ((global::Neurotec.Biometrics.NfeReturnedImage)(this["NfeReturnedImage"]));
            }
            set {
                this["NfeReturnedImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int NfeGeneralizationThreshold {
            get {
                return ((int)(this["NfeGeneralizationThreshold"]));
            }
            set {
                this["NfeGeneralizationThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte NfeGeneralizationMaximalRotation {
            get {
                return ((byte)(this["NfeGeneralizationMaximalRotation"]));
            }
            set {
                this["NfeGeneralizationMaximalRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uint NMMode {
            get {
                return ((uint)(this["NMMode"]));
            }
            set {
                this["NMMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int NMMatchingThreshold {
            get {
                return ((int)(this["NMMatchingThreshold"]));
            }
            set {
                this["NMMatchingThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte NMMaximalRotation {
            get {
                return ((byte)(this["NMMaximalRotation"]));
            }
            set {
                this["NMMaximalRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FPUseG {
            get {
                return ((bool)(this["FPUseG"]));
            }
            set {
                this["FPUseG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int FPGPercent {
            get {
                return ((int)(this["FPGPercent"]));
            }
            set {
                this["FPGPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MatchAllDatabase {
            get {
                return ((bool)(this["MatchAllDatabase"]));
            }
            set {
                this["MatchAllDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAllMatchingResults {
            get {
                return ((bool)(this["ShowAllMatchingResults"]));
            }
            set {
                this["ShowAllMatchingResults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PromptForImageResolution {
            get {
                return ((bool)(this["PromptForImageResolution"]));
            }
            set {
                this["PromptForImageResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchForDuplicates {
            get {
                return ((bool)(this["SearchForDuplicates"]));
            }
            set {
                this["SearchForDuplicates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool NfeUseQuality {
            get {
                return ((bool)(this["NfeUseQuality"]));
            }
            set {
                this["NfeUseQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte NfeQualityThreshold {
            get {
                return ((byte)(this["NfeQualityThreshold"]));
            }
            set {
                this["NfeQualityThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Result")]
        public global::Neurotec.Biometrics.Gui.ShownImage FPShownImage {
            get {
                return ((global::Neurotec.Biometrics.Gui.ShownImage)(this["FPShownImage"]));
            }
            set {
                this["FPShownImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FPShowMinutiae {
            get {
                return ((bool)(this["FPShowMinutiae"]));
            }
            set {
                this["FPShowMinutiae"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 500")]
        public global::System.Drawing.Size NFRecordFromSize {
            get {
                return ((global::System.Drawing.Size)(this["NFRecordFromSize"]));
            }
            set {
                this["NFRecordFromSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NFRecordFormMaximized {
            get {
                return ((bool)(this["NFRecordFormMaximized"]));
            }
            set {
                this["NFRecordFormMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$(FileNameNoExt(Path))")]
        public string ID {
            get {
                return ((string)(this["ID"]));
            }
            set {
                this["ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint ProgramMode {
            get {
                return ((uint)(this["ProgramMode"]));
            }
            set {
                this["ProgramMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveImagesToDatabase {
            get {
                return ((bool)(this["SaveImagesToDatabase"]));
            }
            set {
                this["SaveImagesToDatabase"] = value;
            }
        }
    }
}
