//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCBioVerificationFace {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ExtractorMinIod {
            get {
                return ((int)(this["ExtractorMinIod"]));
            }
            set {
                this["ExtractorMinIod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ExtractorMaxIod {
            get {
                return ((int)(this["ExtractorMaxIod"]));
            }
            set {
                this["ExtractorMaxIod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte ExtractorFaceQuality {
            get {
                return ((byte)(this["ExtractorFaceQuality"]));
            }
            set {
                this["ExtractorFaceQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double ExtractorFaceConfidence {
            get {
                return ((double)(this["ExtractorFaceConfidence"]));
            }
            set {
                this["ExtractorFaceConfidence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public short ExtractorMaxRollAngleDeviation {
            get {
                return ((short)(this["ExtractorMaxRollAngleDeviation"]));
            }
            set {
                this["ExtractorMaxRollAngleDeviation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Large")]
        public global::Neurotec.Biometrics.NleTemplateSize EnrollTemplateSize {
            get {
                return ((global::Neurotec.Biometrics.NleTemplateSize)(this["EnrollTemplateSize"]));
            }
            set {
                this["EnrollTemplateSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Large")]
        public global::Neurotec.Biometrics.NleTemplateSize IdentificationTemplateSize {
            get {
                return ((global::Neurotec.Biometrics.NleTemplateSize)(this["IdentificationTemplateSize"]));
            }
            set {
                this["IdentificationTemplateSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Neurotec.Biometrics.NMatchingSpeed MatcherSpeed {
            get {
                return ((global::Neurotec.Biometrics.NMatchingSpeed)(this["MatcherSpeed"]));
            }
            set {
                this["MatcherSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int MatcherThreshold {
            get {
                return ((int)(this["MatcherThreshold"]));
            }
            set {
                this["MatcherThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ExtractorFavorLargestFace {
            get {
                return ((bool)(this["ExtractorFavorLargestFace"]));
            }
            set {
                this["ExtractorFavorLargestFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ExtractorUseLivenessCheck {
            get {
                return ((bool)(this["ExtractorUseLivenessCheck"]));
            }
            set {
                this["ExtractorUseLivenessCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double ExtractorLivenessCheckThreshold {
            get {
                return ((double)(this["ExtractorLivenessCheckThreshold"]));
            }
            set {
                this["ExtractorLivenessCheckThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ExtractorLiveEnrollFrameCount {
            get {
                return ((int)(this["ExtractorLiveEnrollFrameCount"]));
            }
            set {
                this["ExtractorLiveEnrollFrameCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public short ExtractorMaxYawAngle {
            get {
                return ((short)(this["ExtractorMaxYawAngle"]));
            }
            set {
                this["ExtractorMaxYawAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExtractorDetectAllFeaturesNonLive {
            get {
                return ((bool)(this["ExtractorDetectAllFeaturesNonLive"]));
            }
            set {
                this["ExtractorDetectAllFeaturesNonLive"] = value;
            }
        }
    }
}
